# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        #option 3: Mais attention que les noms soitent très spécifiques!!!!
        # bind:
        #     $omdbToken: '28c5b7b1'
        #     $omdbHost: 'https://www.omdbapi.com'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #option 1: déclaration explicite de service
    # App\OmdbApi:
    #     class: App\OmdbApi
    #     arguments:
    #         $omdbClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
    #         $omdbToken: '28c5b7b1'
    #         $omdbHost: 'https://www.omdbapi.com'

    #option 2: déclaration partielle de service, si on commente le service Symfony sait rechercher le service dont il a besoin
    App\OmdbApi:
        class: App\OmdbApi
        arguments:
            # $omdbClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $omdbToken: '28c5b7b1'
            $omdbHost: 'https://www.omdbapi.com'
            $composerLicense: '%env(key:license:json:file:resolve:COMPOSER_PATH)%' #variable créée dans le fichier .env